package com.rapipay.commonapi.enums;

public enum ServiceTypes {

    MERCHANT_LOGIN,
    MERCHANT_LOGOUT,
    GET_NOTIFICATIONS,
    UPDATE_NOTIFICATIONS,
    COUNT_NOTIFICATIONS,
    GET_ON_HOLD_TRANSACTIONS,
    STATEMENT_OF_ACCOUNT,
    DOWNLOAD_STATEMENT_OF_ACCOUNT,
    STATEMENT_OF_ACCOUNT_SETTINGS,
    GET_STATEMENT_OF_SETTINGS,
    UPLOAD_PROFILE_IMAGE,
    GET_PROFILE_IMAGE,
    UPDATE_PROFILE_DETAILS,
    GET_MERCHANT_DETAILS,
    CHANGE_PASSWORD,
    GET_MERCHANT_TID_DETAILS,
    GET_TRANSACTION_HISTORY_FOR_SPECIFIC_DATE,
    GET_USERS_LIST,
    GET_USER_INFORMATION,
    UPDATE_USER_INFORMATION,
    CREATE_SUB_USER;
}
